import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localFont from "@next/font/local";
import "./globals.css";
import Navbar from "./components/navbar";
import { Provider } from "react-redux";
import { store } from "@/lib/redux/store";
import ReduxProvider from "./components/providers/ReduxProvider";
import { Toaster } from "@/components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });
const lemonMilk = localFont({
  src: [
    {
      path: "../public/fonts/LEMONMILK-Regular.otf",
      weight: "400",
    },
  ],
  variable: "--font-lemonmilk",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${lemonMilk.variable} `}>
        <ReduxProvider>
          <main className="h-full w-full">{children}</main>
          <Toaster />
        </ReduxProvider>
      </body>
    </html>
  );
}
